version: '3'

services:
  app:
    build: .
    container_name: stock_assistant1
    network_mode: host
    ports:
      - "8000:000"
      - "5432:000"
    env_file:
      - env.list
    command: bash -c "uvicorn main:app"
