"""Add table bond

Revision ID: f0e3549ebb15
Revises: a8f3a4de6879
Create Date: 2024-10-05 15:07:02.803649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e3549ebb15'
down_revision: Union[str, None] = 'a8f3a4de6879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond',
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('type_bond', sa.Enum('TQOB', name='typebond'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mat_date', sa.TIMESTAMP(timezone=True), nullable=False, comment='Дата погашения'),
    sa.Column('coupon_value', sa.Float(), nullable=False, comment='купон в валюте'),
    sa.Column('coupon_period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('isin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bond')
    # ### end Alembic commands ###
