"""change fields in stock_prices

Revision ID: a8f3a4de6879
Revises: 3cb3a97e5520
Create Date: 2023-12-16 16:48:33.231475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f3a4de6879'
down_revision: Union[str, None] = '3cb3a97e5520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ticket', sa.String(), nullable=False),
                    sa.Column('datetime', sa.TIMESTAMP(), nullable=False),
                    sa.Column('open', sa.Float(), nullable=False),
                    sa.Column('high', sa.Float(), nullable=False),
                    sa.Column('close', sa.Float(), nullable=False),
                    sa.Column('low', sa.Float(), nullable=False),
                    sa.Column('volume', sa.Integer(), nullable=False),
                    sa.Column('timeframe', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_price')
    # ### end Alembic commands ###
