"""change fields in stock_prices

Revision ID: a8f3a4de6879
Revises: 3cb3a97e5520
Create Date: 2023-12-16 16:48:33.231475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f3a4de6879'
down_revision: Union[str, None] = '3cb3a97e5520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('ticket', sa.String(), nullable=False))
    op.add_column('stock_prices', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.add_column('stock_prices', sa.Column('timeframe', sa.TIMESTAMP(), nullable=False))
    op.drop_column('stock_prices', 'stock')
    op.drop_column('stock_prices', 'time_frame')
    op.drop_column('stock_prices', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('stock_prices', sa.Column('time_frame', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stock_prices', sa.Column('stock', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('stock_prices', 'timeframe')
    op.drop_column('stock_prices', 'datetime')
    op.drop_column('stock_prices', 'ticket')
    # ### end Alembic commands ###
